steps: 

  - label: ":hammer_and_wrench::package: Build and push to ECR"
    env:
      AWS_DEFAULT_REGION: ap-southeast-2
      BUILDKITE_CLEAN_CHECKOUT: true
      TRIGGER_ID: "${BUILDKITE_JOB_ID}"
    agents:
      queue: "agent"
    command: |-
      export BUILD_NUMBER=\$BUILDKITE_BUILD_NUMBER
      ./package_ecr.sh
    
    retry:
      automatic: true

  - block: Approval for Deployment


  - trigger: "simple-sinatra-ecs"
    label: ":rocket: Deploy to ECS"
    build:
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
        BUILD_CREATOR: "${BUILDKITE_BUILD_CREATOR}"
        BUILDKITE_AGENT_NAME: "${BUILDKITE_AGENT_NAME}"
        TRIGGER_ID: "${BUILDKITE_JOB_ID}"

  - wait
    



